services:

  bot:
    container_name: get_price_bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/bot
    ports:
      - "8000:8000"
