services:

  bot:
    container_name: get_price_bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/bot
    ports:
      - "8000:8000"
    depends_on:
      - selenium
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
    command: poetry run python -u get_price_bot/bot.py

  selenium:
    # Если контейнер запускается на ARM (например, Apple M1/M2), используйте образ seleniarm
    # Если контейнер запускается на x86_64 (Intel/AMD), используйте selenium/standalone-chrome:latest
    image: seleniarm/standalone-chromium  # для ARM
    # image: selenium/standalone-chrome:latest  # для x86_64 (Intel/AMD)
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    restart: always
